### ISSUE TITLE
Stacks Governance R+D Lab

### ISSUE THREAD

**Issue by hozzjss** [stacksgov/residence-program#10]
**What's your name/your team's name?* Juliet, Harold, Hoz, Ryeder
**Stacks Governance R+D Lab**

**Best email on which to contact you?**
Harold- 2rowcorridor@gmail.com --
Juliet - juliet.oberding@gmail.com
Hz - info@huzay.tech
Ryeder - lifeisnotscripted@gmail.com

**Personal Statement**
**Decentralized Governance Research Lab**

We’ll focus on R+D in decision making processes, prototyping tools that unlock tangible models for the ecosystem. We’ll use interdisciplinary system designs, closing loops of values that revolve around product development. In our R+D context, the products are system models & tools to achieve them but should also be high value for governance use cases across the ecosystem.

Indigenous approaches to delegation & collaborative scalability will guide our system designs, providing fresh lenses to DAO PoCs, commons & community growth incentive structure models. We’ll also be bringing digital fabrication into prototyping, a focus on local accessibility here will speak to our ultimate goals of building long term power decentralization into our models & tools. We’ll continue our PoCs with Harvard/Oxford research group Metagov, building out community tools for quorums, easy paths of delegation, on & off chain processes etc. MVPs viewable in Stacks Advocates DAO, accessible in the main Stacks discord server!

**End Product**

We’ll deliver both a series of tools & whitepaper to the ecosystem. The whitepaper will provide R+D case studies on system models. The tools will be available to achieve gov models for miner DAOs, community DAOs etc. The tools include: PoC for modular tools for DAO decision making mechanisms. Delegation tool PoC for gathering voices across generators of value. Visualization tool MVP for intrinsic motivation incentives in community growth management. Finally, miner community specific DAO governance tool MVP, designed for accessibility to R+D systems in local lay communities.

**Roadmap (Whole Team Full-time hrs)**
M1
SoW: PoC for community DAO decision making mechanisms in Stacks Advocates DAO.
Deliverables: Documentation for on/off chain combinations in live systems & Open source governance Clarity contracts.
Approx. Timeline: Nov-Feb/300 hours

M2
SoW: Delegation tool PoCs in Stacks Advocates DAO. 
Deliverables: Documentation of live community using the PoCs for streamlining bottom up voices in community representation. Open code for organization tooling pushed to github.
Approx. Timeline: March -May/300 hours

M3
SoW: App chain and PoX-lite based tokens governance tools and MVPs for community engagement with their own token. This tooling prioritized to maximize fair launch potential of emergent app chain & public procurement models in the ecosystem.
Deliverables: Documentation for on/off chain combinations in live systems. Open Source governance Clarity contracts pushed to github.
Approx. Timeline: June - Aug/300 hours

M4
SoW: PoC for indigenous community DAO decision making tools. Excited to bring guidance of elders in a historical council to the STX ecosystem. They maintain Native protocols for fair long term sustainable socioeconomic organization, along w/ balanced male/female power distribution models.
Deliverables: Documentation of impact in communities we’re building with. Open Source tooling code pushed to github.
Approx. Timeline: Concurrent w/M1-M3  Nov - Aug/~900 hours

M5
SoW: R+D Whitepaper for System Design Models. Our interdisciplinary System design case studies will be included. Showing benefits of closed loops of unalienated value creation & flow not found in conventional product design.
Deliverables: Documentation of live communities using our PoCs & Firesides Published for ecosystem access.
Approx. Timeline: Sept-Nov/300 hours

**Appendix**
**Roles:** 
**R+D M1-M5**-- Harold, Hz, Juliet
**Communications & Ops R+D M1-M5** -- Ryeder 

- 1st place Winners in Harvard/Oxford Hackathon!: https://metagov.github.io/open-web-challenge/
- [Advocates DAO](https://discord.gg/53UXfUk5) in Stacks Discord Server
- Roundtable w/Stacks Ecosystem Entities & Follow up interviews.
- Stacks Foundation Governance [Working Group Research](https://stacksgov.github.io/resources/#/)
- Indigenous Digital Fabrication [Platform](https://harolddavis3.github.io/Two-Row-Wampum-Social-Layer-Platform/#/)

**Comment by jennymith** [comment]
For all community members interested in keeping up with the Stacks Gov Lab's residency, check out their upcoming plans and follow this thread for weekly updates from @hozzjss, @HaroldDavis3, @joberding, and Ryder themselves:

### Scope of Work

**Background**

The Governance Lab will bring indigenous commons & governance research and development to web3 and the Stacks ecosystem, enabling more accurate community representation through intersecting relationships, skills, & contributions of its members. The Advocates DAO will be used to gather voices & organize the ecosystem sustainably long term.

**Upcoming Milestones**
- By the middle of December as a Stacks community member you should have seamless onboarding to the advocates program, so that you can be rewarded for your contributions to the Stacks ecosystem.
- By the middle of February as a Stacks advocate you should be able to participate in a governance process so that you can make your voice visible to the community in many possible forms: Community grants, community policies, wieghts of rewards in the advocates algorithm, etc.

**Comment by Jolie-Ze** [comment]
Here's a little update!

**By the middle of December as a Stacks community member you should have seamless onboarding to the advocates program, so that you can be rewarded for your contributions to the Stacks ecosystem.**

- Published the first #start-here channel for onboarding and to state the lineage of the Advocates program and emergence
- Fully automated onboarding program to the Stacks Advocates program on Discord
- Enabled advocates to interview new comers themselves further decentralizing the operations of the advocates program

**By the middle of February as a Stacks advocate you should be able to participate in a governance process so that you can make your voice visible to the community in many possible forms: Community grants, community policies, weights of rewards in the advocates algorithm, etc.**

- Initiated collective development of Advocates CoC to clarify behaviour and conduct foundational to governance processes
- Added an active issues channel to address advocates-wide issues in a consensus based model for governance as a starting point
-  Been down on the research path with the consensus flow spec document 3hrs weekly
-  Facilitated weekly meetings for more community involvement with the governance lab through our scheduled events
-  Developed a [Gov Lab calendar](https://bit.ly/gov-lab-cal) to clarify the Lab's role in the ecosystem and to designate our events
- Began weekly dialogue with research collaborators - the Five Nations longhouse - in addition to weekly internal dialogues regarding the wolf-turtle-bear systems protocol

**Comment by HaroldDavis3** [comment]
### Big Gov Lab News!

**AdvoxDAO Soon to implement MicroDAOs**
As we roll out our first uses of our consensus flow tooling for decision making, Hozz has also been heads down the last couple weeks on the temporarily named 'Distacular bot' enabling on-chain transactions right inside discord for AdvoxDAO users. Short readable and open source Clarity contracts enabling users to send stx to on another with their .btc names. Also users can create on-chain funding proposals, create microDAOs, execute funding on DAOs etc. We are super excited for implementing this tooling in combination with our bottom up quorum tooling already in use. We believe this can give us a unique approach to Advox task creation but also our first steps at supporting accessibility to the Ambassadors & Stacks Grants programs! 

<img width="854" alt="image" src="https://user-images.githubusercontent.com/47930890/162258547-0ea46807-f0cc-4aed-a354-df13678d0aea.png">

**Advox Buddy System** 
Any new server can be overwhelming, it is nice to meet brilliant folks in the Stacks ecosystem to walk us through the exciting things happening. HeroGamer of Advox recognized there is a lot to share and we can design for this warm feeling of getting comfortable in the server by meeting someone new to show newcomers around AdvoxDAO events, working groups, tooling etc. This can not be overstated as a critical point of engendering culture for long term resilience & sustainability. We can't express the gratitude for HeroGamer's passionate leadership in this effort. We already have a team formed akin to our welcoming team, ensuring folks coming in have a full welcoming.
Come join us! Never been by the Advocates DAO? You can 🏁│[start-here](https://discord.com/channels/621759717756370964/916371047102705704)
